name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v5

    - name: Set up Go
      uses: actions/setup-go@v6
      with:
        go-version: '1.25'

    - name: Download dependencies
      run: go mod download

    - name: Build
      run: go build -v -o ore${{ matrix.os == 'windows-latest' && '.exe' || '' }} ./cmd/ore

    - name: Test help command
      run: ./ore${{ matrix.os == 'windows-latest' && '.exe' || '' }} --help
      shell: bash

    - name: Upload binary
      uses: actions/upload-artifact@v4
      with:
        name: ore-${{ matrix.os }}
        path: ore${{ matrix.os == 'windows-latest' && '.exe' || '' }}
        retention-days: 7
