name: Multi-Platform Gem Installation

on:
  workflow_dispatch: # Manual trigger for testing
  pull_request:
    paths:
      - '.github/workflows/multi-platform.yml'

# Prevent concurrent runs to avoid cache conflicts
concurrency:
  group: multi-platform-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: MRI on Ubuntu
            os: ubuntu-latest
            ruby: '3.4'

          - name: JRuby on Ubuntu
            os: ubuntu-latest
            ruby: 'jruby-head'

          - name: TruffleRuby on Ubuntu
            os: ubuntu-latest
            ruby: 'truffleruby-head'

          - name: MRI on macOS
            os: macos-latest
            ruby: '3.4'

    name: ${{ matrix.name }}
    steps:
      - uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}

      - name: Install ore
        run: |
          curl -fsSL https://raw.githubusercontent.com/contriboss/ore-light/master/scripts/install.sh | bash
          echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: Verify ore installation
        run: ore version

      - name: Create multi-platform Gemfile
        run: |
          mkdir -p test-multiplatform && cd test-multiplatform
          cat > Gemfile <<'EOF'
          source 'https://rubygems.org'

          gem 'rack', '~> 3.0'
          gem 'sinatra', '~> 4.0'

          # MRI-specific gems (C extensions)
          platform :mri do
            gem 'pg', '~> 1.5'
          end

          # JRuby-specific gems (Java adapters)
          platform :jruby do
            gem 'jdbc-postgres', '~> 42.0'
          end
          EOF

      - name: Generate multi-platform lockfile
        run: |
          cd test-multiplatform
          ore lock \
            --add-platform x86_64-linux \
            --add-platform aarch64-linux \
            --add-platform x86_64-darwin \
            --add-platform aarch64-darwin \
            --add-platform java

      - name: Install gems
        run: |
          cd test-multiplatform
          ore install

      - name: Test gem loading
        run: |
          cd test-multiplatform
          ruby -e "
            require 'bundler/setup'
            require 'rack'
            require 'sinatra/base'

            puts '✅ Core gems loaded successfully!'
            puts 'Rack version: ' + Rack::VERSION
            puts 'Sinatra version: ' + Sinatra::VERSION

            # Platform-specific tests
            if RUBY_ENGINE == 'jruby'
              require 'jdbc/postgres'
              puts '✅ JRuby gems loaded successfully!'
              puts 'JDBC Postgres version: ' + Jdbc::Postgres::VERSION
            elsif RUBY_ENGINE != 'truffleruby'
              require 'pg'
              puts '✅ MRI gems loaded successfully!'
              puts 'pg version: ' + PG::VERSION
            else
              puts '✅ TruffleRuby detected (skipping platform-specific gems)'
            end
          "
