name: release-please

on:
  push:
    branches:
      - master
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: googleapis/release-please-action@v4
        id: release
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Checkout
        if: ${{ steps.release.outputs.release_created }}
        uses: actions/checkout@v5

      - name: Setup Go
        if: ${{ steps.release.outputs.release_created }}
        uses: actions/setup-go@v6
        with:
          go-version-file: "go.mod"

      - name: Install Mage
        if: ${{ steps.release.outputs.release_created }}
        run: go install github.com/magefile/mage@latest

      - name: Run full CI validation
        if: ${{ steps.release.outputs.release_created }}
        run: mage ci

      - name: Trigger Release workflow
        if: ${{ steps.release.outputs.release_created }}
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Re-push the tag to trigger the Release workflow
          # (release-please creates tags via API which doesn't fire push:tags)
          TAG="${{ steps.release.outputs.tag_name }}"
          git push origin ":refs/tags/$TAG" || true
          git tag -f "$TAG"
          git push origin "$TAG"
