source 'https://rubygems.org'

# Default group gems
gem 'json'
gem 'concurrent-ruby'

group :development do
  gem 'rake'
  gem 'minitest'
end

group :test do
  gem 'simplecov'
end

group :development, :test do
  gem 'benchmark'
end
